### ISSUE TITLE
Bug when running custom python screet

### ISSUE THREAD

**Issue by eliecer696** [UPBGE/UPBGE-logicnodes#70]
this is wile using the Run Python Code node
this is what the debug outputs 

version 2.1.0

[ERROR] KX_PythonComponent[NodeTree] - Failed to invoke the update callback.
Traceback (most recent call last):
  File ".blend\nl_nodetree.py", line 63, in update
  File ".blend\nl_nodetree.py", line 44, in evaluate
  File "C:\Users\----\-----\Desktop\Release\3.4\python\lib\site-packages\uplogic\nodes\logictree.py", line 245, in evaluate
    cell.evaluate()
  File "C:\----\-----\----\Desktop\Release\3.4\python\lib\site-packages\uplogic\nodes\actions\runpython.py", line 45, in evaluate
    self._modfun = getattr(self._module, mfun)
AttributeError: module 'myScript' has no attribute ''
Blender Game Engine Finished

**Comment by IzaZed** [comment]
How does your script and node setup look?
