### ISSUE TITLE
local server node problem 

### ISSUE THREAD

**Issue by eliecer696** [UPBGE/UPBGE-logicnodes#81]
server start with out any problem but when a client connects it shoots an error here is my node set up
logic nodes vs 2.3
blender 3.3

Exception in thread Thread-15 (update):
Traceback (most recent call last):
  File "D:\Release\3.3\python\lib\site-packages\uplogic\network\server.py", line 123, in update
    print(f"Connected to: {add}")
  File "D:\Release\3.3\python\lib\site-packages\uplogic\logging\__init__.py", line 42, in write
    log(__s)
  File "D:\Release\3.3\python\lib\site-packages\uplogic\logging\__init__.py", line 146, in log
    logger.add_message(f'{msg}', type, time=show_time)
  File "D:\Release\3.3\python\lib\site-packages\uplogic\logging\__init__.py", line 115, in add_message
    self.layout.add_widget(Label(text=f'>{current_time}  {msg}', pos=[5, 10], font_color=self.colors[type]))
  File "D:\Release\3.3\python\lib\site-packages\uplogic\ui\widget.py", line 364, in add_widget
    widget.parent = self
  File "D:\Release\3.3\python\lib\site-packages\uplogic\ui\widget.py", line 129, in parent
    self.build_shader()
  File "D:\Release\3.3\python\lib\site-packages\uplogic\ui\widget.py", line 330, in build_shader
    self._batch = batch_for_shader(self._shader, 'TRIS', {"pos": vertices}, indices=indices)
  File "D:\Release\3.3\scripts\modules\gpu_extras\batch.py", line 39, in batch_for_shader
    vbo.attr_fill(id, data)
ValueError: Unknown attribute name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Release\3.3\python\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "D:\Release\3.3\python\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Release\3.3\python\lib\site-packages\uplogic\network\server.py", line 138, in update
    print(e, 'Exception')
  File "D:\Release\3.3\python\lib\site-packages\uplogic\logging\__init__.py", line 42, in write
    log(__s)
  File "D:\Release\3.3\python\lib\site-packages\uplogic\logging\__init__.py", line 146, in log
    logger.add_message(f'{msg}', type, time=show_time)
  File "D:\Release\3.3\python\lib\site-packages\uplogic\logging\__init__.py", line 115, in add_message
    self.layout.add_widget(Label(text=f'>{current_time}  {msg}', pos=[5, 10], font_color=self.colors[type]))
  File "D:\Release\3.3\python\lib\site-packages\uplogic\ui\widget.py", line 364, in add_widget
    widget.parent = self
  File "D:\Release\3.3\python\lib\site-packages\uplogic\ui\widget.py", line 129, in parent
    self.build_shader()
  File "D:\Release\3.3\python\lib\site-packages\uplogic\ui\widget.py", line 330, in build_shader
    self._batch = batch_for_shader(self._shader, 'TRIS', {"pos": vertices}, indices=indices)
  File "D:\Release\3.3\scripts\modules\gpu_extras\batch.py", line 39, in batch_for_shader
    vbo.attr_fill(id, data)
ValueError: Unknown attribute name

**Comment by IzaZed** [comment]
this is a problem with printing, so the same thing should happen if you use the print node
you can try updating to 0.36 stable release of UPBGE, it seems to work there
