### ISSUE TITLE
set object transform node broken

### ISSUE THREAD

**Issue by Sanocon** [UPBGE/UPBGE-logicnodes#84]
so i try to use the set position/rotation/scale node in transform mode and I get this log when using it.

`[ERROR] KX_PythonComponent[Logic_Node_Editor] - Failed to invoke the start callback.
Traceback (most recent call last):
  File ".blend\nl_logic_node_editor.py", line 62, in start
  File ".blend\nl_logic_node_editor.py", line 45, in evaluate
  File "C:\Users\david\Downloads\upbge-0.36-windows-x86_64\3.6\python\lib\site-packages\uplogic\nodes\logictree.py", line 219, in evaluate
    cell.evaluate()
  File "C:\Users\david\Downloads\upbge-0.36-windows-x86_64\3.6\python\lib\site-packages\uplogic\nodes\actions\setgameobjectattr.py", line 49, in evaluate
    setattr(
SystemError: <built-in function setattr> returned NULL without setting an exception`

**Comment by IzaZed** [comment]
Is this still an issue in the new 4.1 version?

**Comment by NTNfst** [comment]
upbge-0.36.1-windows-x86_64
and logic nodes+ 2.3
