### ISSUE TITLE
The logic node aren't working

### ISSUE THREAD

**Issue by Fungaming51** [UPBGE/UPBGE-logicnodes#93]
When I apply the node tree to the selected object and press play and press any button or move my mouse the object won't move despite it being programed via the logic nodes.

**Comment by IzaZed** [comment]
Are you getting error messages?
And did you make sure uplogic is installed via the Addon Preferences?

**Comment by Fungaming51** [comment]
sorry for the extremly late reply.

I just checked and got this error message:
  "[ERROR] KX_PythonComponent[player_controls] - Failed to invoke the start callback.
Traceback (most recent call last):
  File "C:\Users\[user]\Desktop\f\games\The Family\The Granny\The Granny.blend\nl_player_controls.py", line 176, in start
  File "C:\Users\[user]\Desktop\f\games\The Family\The Granny\The Granny.blend\nl_player_controls.py", line 102, in __init__
AttributeError: 'ULObjectAttribute' object has no attribute 'VEC'
[ERROR] KX_PythonComponent[collicetable] - Failed to invoke the start callback.
Traceback (most recent call last):
  File "C:\Users\[user]\Desktop\f\games\The Family\The Granny\The Granny.blend\nl_collicetable.py", line 80, in start
  File "C:\Users\[user]\Desktop\f\games\The Family\The Granny\The Granny.blend\nl_collicetable.py", line 42, in __init__
AttributeError: 'ULObjectAttribute' object has no attribute 'VEC'"

And I have Logic Nodes  installed.
